// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBvjnrynMeHb1xp4AcKER52S1L8_nO1d6I',
    appId: '1:318775788354:web:4fb21e65c90b0011753edb',
    messagingSenderId: '318775788354',
    projectId: 'liquid-logistics',
    authDomain: 'liquid-logistics.firebaseapp.com',
    storageBucket: 'liquid-logistics.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCtszVk23oPXOOIncyXhkApLWiPkwaEt4g',
    appId: '1:318775788354:android:15f8010b397e848b753edb',
    messagingSenderId: '318775788354',
    projectId: 'liquid-logistics',
    storageBucket: 'liquid-logistics.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBUNyaCJdT6B0fF8iHtmptmBjoyFV6vS1M',
    appId: '1:318775788354:ios:41a124206f3a09ec753edb',
    messagingSenderId: '318775788354',
    projectId: 'liquid-logistics',
    storageBucket: 'liquid-logistics.firebasestorage.app',
    iosBundleId: 'com.example.liquidLogistics',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBUNyaCJdT6B0fF8iHtmptmBjoyFV6vS1M',
    appId: '1:318775788354:ios:41a124206f3a09ec753edb',
    messagingSenderId: '318775788354',
    projectId: 'liquid-logistics',
    storageBucket: 'liquid-logistics.firebasestorage.app',
    iosBundleId: 'com.example.liquidLogistics',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBvjnrynMeHb1xp4AcKER52S1L8_nO1d6I',
    appId: '1:318775788354:web:764a99fd3469ad24753edb',
    messagingSenderId: '318775788354',
    projectId: 'liquid-logistics',
    authDomain: 'liquid-logistics.firebaseapp.com',
    storageBucket: 'liquid-logistics.firebasestorage.app',
  );
}



